const express = require('express');
const router = express.Router();

const { exportLogController } = require('../controllers');
router.get('/adyen', exportLogController.adyen.get);
router.post('/adyen', exportLogController.adyen.post);
router.get('/coda', exportLogController.coda.get);
router.post('/coda', exportLogController.coda.post);
router.get('/gash', exportLogController.gash.get);
router.post('/gash', exportLogController.gash.post);
router.get('/gocpay', exportLogController.gocpay.get);
router.post('/gocpay', exportLogController.gocpay.post);
router.get('/gudang', exportLogController.gudang.get);
router.post('/gudang', exportLogController.gudang.post);
router.get('/mycard', exportLogController.mycard.get);
router.post('/mycard', exportLogController.mycard.post);
router.get('/molglobal', exportLogController.molglobal.get);
router.post('/molglobal', exportLogController.molglobal.post);
router.get('/molthai', exportLogController.molthai.get);
router.post('/molthai', exportLogController.molthai.post);
router.get('/payermax', exportLogController.payermax.get);
router.post('/payermax', exportLogController.payermax.post);
router.get('/paypal', exportLogController.paypal.get);
router.post('/paypal', exportLogController.paypal.post);
router.get('/unipin', exportLogController.unipin.get);
router.post('/unipin', exportLogController.unipin.post);
module.exports = router;
